language: node_js
node_js:
  - "5"
before_script:
  - 'npm install -g gulp'
  - 'npm install'
script:
  - npm run test:lint
  - npm run test:coverage
  - npm test
after_success:
  - 'npm run coveralls'
